S1T4: Notification settings rest service: change request mapping, add property to User class.
undsett/CityElf pull request #21
Opened 2017-05-17 17:17 UTC by greySlon

2017-05-19 16:43 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/repository/NotificationRepository.java
> +      return null;
if you return **null** from the method, you should consider Java 8 Optional class

2017-05-19 16:44 UTC, parkhomenko requested changes
Correct one point I mentioned and change the commit message. It should be defined for a new defect, not the US you have already submitted before.

2017-05-20 10:23 UTC, parkhomenko requested changes
Could you change the commit message to "S1T4 [Defect_1]: Settings by user id doesn't work" as it is written in the card in trello.

2017-05-20 14:13 UTC, greySlon commented
готово

2017-05-20 20:15 UTC, parkhomenko approved these changes

2017-05-20 20:15 UTC, merged