Task: Add database support for NotificationService
undsett/CityElf pull request #29
Opened 2017-05-29 22:58 UTC by greySlon

2017-05-30 17:08 UTC, parkhomenko requested changes
Everything is fine, but let's wait until Anton creates a database schema and connect a real db here.
I'll let you know when he finishes.

2017-06-13 21:54 UTC, greySlon commented
I deleted previous task (Task: Add database support for NotificationService) as   it was out of date (we have NotificationRepository no more). Also I've  commented tests that failed over hibernate untill  issue is solved.

2017-06-14 10:20 UTC, greySlon commented
Tests work

2017-06-14 15:07 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/NumberExtractor.java
> +package com.cityelf.model.water.parser;
Move it from model to utils folder

2017-06-14 15:08 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/NumberExtractor.java
> +  private String streetReplacePattern = ".+?,";
You can make the next to variable final

2017-06-14 15:09 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/NumberExtractor.java
> +    Set<String> set = new TreeSet<>();
Better not to name variables just as **set** or **string**

2017-06-14 15:10 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/Parser.java
> +package com.cityelf.model.water.parser;
Move it to utils package

2017-06-14 15:11 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/Place.java
> +package com.cityelf.model.water.parser;
Since it is not database related class, let's move it to a domain package (create another folder domain in the com/cityelf)

2017-06-14 15:11 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/Report.java
> +package com.cityelf.model.water.parser;
Move to domain package

2017-06-14 15:12 UTC, parkhomenko commented on src/main/java/com/cityelf/model/water/parser/StreetExtractor.java
> +    } else {
You don't need "else" here, just the exception.

2017-06-15 11:06 UTC, parkhomenko approved these changes

2017-06-15 11:08 UTC, merged