S3T2: Create a rest service with CRUD operations for water shutdowns
undsett/CityElf pull request #33
Opened 2017-06-14 07:15 UTC by DmitriyOsipov

1. Here is no tests, but I'm working on them
2. If we try to create some water forecast with nonexistent address hibernate will throw an exception. I don't catch it and I don't check an address for existing.
3. We can't add a new forecast with the same start time and address
4. for controllers: 
     /waterForecast/get?start=yyyy-mm-ddThh-mm-ss&address=stringAddress - get the forecast with specified startTime and address
     /waterForecast/getByStart and /waterForecast/getAddressesByTime are called like 
`_link_?start=yyyy-mm-ddThh-mm-ss` - return the List of forecasts with specified start time and the Set of Addresses respectively

2017-06-14 07:19 UTC, DmitriyOsipov commented
I also added new dependency:
`compile('com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.8.8')`
to the build.gradle
and added my controller to the SmokeTest

2017-06-14 18:02 UTC, DmitriyOsipov commented
Added tests

2017-06-15 11:16 UTC, parkhomenko commented on src/main/java/com/cityelf/controller/WaterForecastController.java
> +@RequestMapping("/waterForecast")
Let's not use uppercase letters in urls

2017-06-15 11:17 UTC, parkhomenko commented on src/main/java/com/cityelf/controller/WaterForecastController.java
> +  @RequestMapping(value = "/{wfId}", method = RequestMethod.GET)
Shorten it to **id** from **wfId**

2017-06-15 11:18 UTC, parkhomenko commented on src/main/java/com/cityelf/controller/WaterForecastController.java
> +  @RequestMapping(value = "/getByStart", method = RequestMethod.GET)
The same as above for uppercase letters, let's get rid of them. Just **getbystart**

2017-06-15 11:23 UTC, parkhomenko commented on src/main/java/com/cityelf/controller/WaterForecastController.java
> +  @RequestMapping(value = "/update", method = RequestMethod.POST)
Use **Request.PUT** method for update operations

2017-06-15 11:24 UTC, parkhomenko commented on src/main/java/com/cityelf/controller/WaterForecastController.java
> +  @RequestMapping(value = "/delete", method = RequestMethod.POST)
Use **RequestMethod.DELETE** for delete operations

2017-06-15 11:24 UTC, parkhomenko commented on src/main/java/com/cityelf/controller/WaterForecastController.java
> +  @RequestMapping(value = "/deleteAllByTime", method = RequestMethod.POST)
The same as above

2017-06-15 11:25 UTC, parkhomenko commented on src/main/java/com/cityelf/model/Address.java
> +  @Column(name = "street")
It'll look better if you add an extra empty line between the previous and the next property.
The same for all other entity classes below.

2017-06-15 11:26 UTC, parkhomenko commented on src/main/java/com/cityelf/model/WaterForecast.java
> +  private long id;
Add extra space between properties lines

2017-06-15 11:27 UTC, parkhomenko commented on src/main/java/com/cityelf/model/WaterForecast.java
> +  @OneToOne
This is not @OneToOne relationship. It is @ManyToOne, since you can have a lot of the same address_id in the water_forecasts table.

2017-06-15 11:29 UTC, parkhomenko commented on src/main/java/com/cityelf/service/WaterForecastService.java
> +  //Get all water forecasts in repository. If we clear repository every few hours, it will return only
Use javadoc format for all the comments.

2017-06-15 11:30 UTC, parkhomenko commented on src/main/java/com/cityelf/service/WaterForecastService.java
> +  public WaterForecastService() {
No need for default constructor if there is no other one. It will be added by the compiler automatically.

2017-06-15 11:31 UTC, parkhomenko commented on src/main/java/com/cityelf/service/WaterForecastService.java
> +    } else {
You don't need **else** the same as in the other similar constructors. It is not a mistake, just a redundancy.

2017-06-15 11:36 UTC, parkhomenko requested changes
Everything is great. Just fix my comments.
One more thing:
we should add one more rest which doesn't take any parameters but returns all current forecasts for current time (you can use LocalDateTime's now functions to get it)

2017-06-16 07:19 UTC, DmitriyOsipov commented
I fixed your comments and added a one more rest.

2017-06-16 07:27 UTC, parkhomenko approved these changes

2017-06-16 07:28 UTC, merged