Develop
undsett/CityElf pull request #35
Opened 2017-06-18 20:04 UTC by ATsurkanu

GasForecasts API and test for it was added.

2017-06-19 16:59 UTC, parkhomenko commented on build.gradle
> +    compile('org.springframework.boot:spring-boot-starter-web')
Did you change anything in this file?

2017-06-19 17:00 UTC, parkhomenko commented on src/main/java/com/cityelf/model/Address.java
> +    @Column(name = "street")
You don't have to change formatting in existing files.

2017-06-19 17:01 UTC, parkhomenko commented on src/main/java/com/cityelf/model/User.java
> +import java.time.LocalDateTime;
We should return the order as it was

2017-06-19 17:02 UTC, parkhomenko commented on src/main/java/com/cityelf/model/WaterForecast.java
> +    @Id
Again, you changed formatting, no real changes...

2017-06-19 17:04 UTC, parkhomenko requested changes
Everything is fine, just lots of issues due to correcting formatting in already existing code.
Also, remove jar libraries from the commit.

2017-06-19 19:04 UTC, ATsurkanu commented on build.gradle
> +    compile('org.springframework.boot:spring-boot-starter-web')
No, I did nothing.

2017-06-19 19:06 UTC, ATsurkanu commented on src/main/java/com/cityelf/model/User.java
> +import java.time.LocalDateTime;
Ok

2017-06-19 19:06 UTC, ATsurkanu commented on src/main/java/com/cityelf/model/Address.java
> +    @Column(name = "street")
Ok

2017-06-23 15:44 UTC, parkhomenko approved these changes

2017-06-23 15:47 UTC, merged