Notification settings
undsett/CityElf pull request #4
Opened 2017-04-24 22:00 UTC by greySlon

2017-04-27 06:43 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/controller/UserController.java
> +    private UserService us;
change variable to **userService** instead of **us**

2017-04-27 06:44 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/controller/UserController.java
> +    public java.util.List<User> getAll() {
import java.util.List instead of using it directly

2017-04-27 06:45 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/repository/IRepository.java
> + * Created by Sergii on 26.04.2017.
This comment is redundant. Git saves all the information about who changed the file and when.
Disable automatic insertion of that thing in idea.

2017-04-27 06:47 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/repository/IRepository.java
> +public interface IRepository {
This is not a java way of creating an interface. Do not use **I** before it.
Also just the word **Repository** means nothing. Change it to Notification repository.
Moreover you don't need to create an interface if you have just one implementation. You can easily add one if it's needed in the future by the means of IDE.

2017-04-27 06:50 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/repository/UserRepository.java
> +    private List<User> users = new ArrayList();
This file hasn't been changed at all. We will add the correct formatting styles.
Just return back 2 spaces indentation as it was for now.
We will discuss that thing. Styling is very important.

2017-04-27 06:51 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/service/UserService.java
> +public class UserService {
Again, you haven't changed anything in this file. Please, disregard the changes

2017-04-27 06:52 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/service/IRepositoryImpl.java
> +public class IRepositoryImpl implements IRepository {
It should be Notification Repository with the annotation **@Repository** without any implementations

2017-04-27 06:52 UTC, parkhomenko commented on cityelf/src/main/java/com/cityelf/service/IRepositoryImpl.java
> + * Created by Sergii on 26.04.2017.
Delete the comment

2017-04-27 06:52 UTC, parkhomenko requested changes
Please correct my points

2017-04-27 19:28 UTC, greySlon commented
исправлено

2017-04-28 09:09 UTC, parkhomenko approved these changes

2017-04-28 09:10 UTC, merged