Develop
undsett/CityElf pull request #40
Opened 2017-06-21 17:26 UTC by DmitriyOsipov

2017-06-21 17:48 UTC, parkhomenko commented on src/main/java/com/cityelf/utils/GasLoader.java
> +          new Throwable("Gas page structure was changed"));
Why do you need to create a new Throwable here?

2017-06-21 17:50 UTC, parkhomenko commented on src/test/java/com/cityelf/utils/ParserGasTest.java
> +    File file = new File(".\\src\\test\\java\\com\\cityelf\\utils\\gasWebResponseTest.txt");
You have to move this file into the test\resources folder. This folder is exactly for such files.
Look here how to read it then:
https://www.mkyong.com/java/java-read-a-file-from-resources-folder/

2017-06-21 17:51 UTC, parkhomenko commented on src/main/java/com/cityelf/utils/GasForecaster.java
> +  void setStreetExtractor(StreetExtractor streetExtractor) {
Why do you have some function without access modifier?

2017-06-21 17:52 UTC, parkhomenko requested changes
Fix some minor issues.

2017-06-21 19:26 UTC, DmitriyOsipov commented on src/main/java/com/cityelf/utils/GasForecaster.java
> +  void setStreetExtractor(StreetExtractor streetExtractor) {
here was two setters which I didn't use, so I removed them

2017-06-21 19:27 UTC, DmitriyOsipov commented on src/test/java/com/cityelf/utils/ParserGasTest.java
> +    File file = new File(".\\src\\test\\java\\com\\cityelf\\utils\\gasWebResponseTest.txt");
Done.
Also I added two tests for start and end dates

2017-06-21 19:55 UTC, DmitriyOsipov commented on src/main/java/com/cityelf/utils/GasLoader.java
> +          new Throwable("Gas page structure was changed"));
I added a new exception type: GasPageStructureChangedException. It will be more logical

2017-06-23 15:39 UTC, parkhomenko approved these changes

2017-06-23 15:39 UTC, merged