S5T1: Service for transfer data from parsers to DB
undsett/CityElf pull request #47
Opened 2017-07-03 03:08 UTC by greySlon

here is ForecastCollector that collect necessary data to create the forcasts from all  of the parsers, sends them further for user notification and rewrites forecasts in tables in database. It will be started from some REST service.

2017-07-03 08:27 UTC, parkhomenko commented on src/main/java/com/cityelf/utils/ForecastCollector.java
> +      ex.printStackTrace();
Let's add a logger, so the error messages are written in some file

2017-07-03 08:30 UTC, parkhomenko requested changes
Everything is great. Just add a controller with a single method which starts your forecast collector. The mapping could be something like "/forecasts/collector/start".

2017-07-03 22:04 UTC, greySlon commented
Added controller and logging in ForecastCollector(console out only)
Tried to get output in file but there were some difficulties - standart logger configuration worked and my configuration never applied()

2017-07-04 12:46 UTC, parkhomenko approved these changes

2017-07-04 12:48 UTC, merged

2017-07-04 12:48 UTC, parkhomenko commented
We can skip logging in file for now.